//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\code\antlr\AntlrCSharp\Antlr\Create.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CreateParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface ICreateVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CreateParser.create"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate([NotNull] CreateParser.CreateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CreateParser.with"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWith([NotNull] CreateParser.WithContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CreateParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] CreateParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CreateParser.propertydeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertydeclaration([NotNull] CreateParser.PropertydeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CreateParser.declarationlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarationlist([NotNull] CreateParser.DeclarationlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CreateParser.identifiernamedeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifiernamedeclaration([NotNull] CreateParser.IdentifiernamedeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CreateParser.identifiertype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifiertype([NotNull] CreateParser.IdentifiertypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CreateParser.createType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreateType([NotNull] CreateParser.CreateTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CreateParser.class"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass([NotNull] CreateParser.ClassContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CreateParser.interface"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface([NotNull] CreateParser.InterfaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CreateParser.record"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecord([NotNull] CreateParser.RecordContext context);
}
