//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:\Git\Other\AntlrMiniProject\AntlrCSharp\Antlr\Create.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class CreateLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, UPPERCASE=9, 
		LOWERCASE=10, DIGIT=11, PROPERTY=12, IDENTIFIER=13, WORD=14, WHITESPACE=15;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "UPPERCASE", 
		"LOWERCASE", "DIGIT", "UNDERSCORE", "IDENTIFIERFIRST", "IDENTIFIERNOTFIRST", 
		"PROPERTY", "IDENTIFIER", "WORD", "WHITESPACE"
	};


	public CreateLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public CreateLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'create'", "'with'", "','", "':'", "'?'", "'class'", "'interface'", 
		"'record'", null, null, null, "'property'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, "UPPERCASE", "LOWERCASE", 
		"DIGIT", "PROPERTY", "IDENTIFIER", "WORD", "WHITESPACE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Create.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static CreateLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x11', '~', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', 
		'\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', 
		'\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x5', '\xE', 
		'\\', '\n', '\xE', '\x3', '\xF', '\x3', '\xF', '\x5', '\xF', '`', '\n', 
		'\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x11', '\x3', '\x11', '\a', '\x11', 'm', '\n', '\x11', '\f', '\x11', 
		'\xE', '\x11', 'p', '\v', '\x11', '\x3', '\x12', '\x3', '\x12', '\x6', 
		'\x12', 't', '\n', '\x12', '\r', '\x12', '\xE', '\x12', 'u', '\x3', '\x13', 
		'\x6', '\x13', 'y', '\n', '\x13', '\r', '\x13', '\xE', '\x13', 'z', '\x3', 
		'\x13', '\x3', '\x13', '\x2', '\x2', '\x14', '\x3', '\x3', '\x5', '\x4', 
		'\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', 
		'\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\x2', '\x1B', 
		'\x2', '\x1D', '\x2', '\x1F', '\xE', '!', '\xF', '#', '\x10', '%', '\x11', 
		'\x3', '\x2', '\x6', '\x3', '\x2', '\x43', '\\', '\x3', '\x2', '\x63', 
		'|', '\x3', '\x2', '\x32', ';', '\x4', '\x2', '\v', '\v', '\"', '\"', 
		'\x2', '\x81', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x3', '\'', '\x3', 
		'\x2', '\x2', '\x2', '\x5', '.', '\x3', '\x2', '\x2', '\x2', '\a', '\x33', 
		'\x3', '\x2', '\x2', '\x2', '\t', '\x35', '\x3', '\x2', '\x2', '\x2', 
		'\v', '\x37', '\x3', '\x2', '\x2', '\x2', '\r', '\x39', '\x3', '\x2', 
		'\x2', '\x2', '\xF', '?', '\x3', '\x2', '\x2', '\x2', '\x11', 'I', '\x3', 
		'\x2', '\x2', '\x2', '\x13', 'P', '\x3', '\x2', '\x2', '\x2', '\x15', 
		'R', '\x3', '\x2', '\x2', '\x2', '\x17', 'T', '\x3', '\x2', '\x2', '\x2', 
		'\x19', 'V', '\x3', '\x2', '\x2', '\x2', '\x1B', '[', '\x3', '\x2', '\x2', 
		'\x2', '\x1D', '_', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x61', '\x3', 
		'\x2', '\x2', '\x2', '!', 'j', '\x3', '\x2', '\x2', '\x2', '#', 's', '\x3', 
		'\x2', '\x2', '\x2', '%', 'x', '\x3', '\x2', '\x2', '\x2', '\'', '(', 
		'\a', '\x65', '\x2', '\x2', '(', ')', '\a', 't', '\x2', '\x2', ')', '*', 
		'\a', 'g', '\x2', '\x2', '*', '+', '\a', '\x63', '\x2', '\x2', '+', ',', 
		'\a', 'v', '\x2', '\x2', ',', '-', '\a', 'g', '\x2', '\x2', '-', '\x4', 
		'\x3', '\x2', '\x2', '\x2', '.', '/', '\a', 'y', '\x2', '\x2', '/', '\x30', 
		'\a', 'k', '\x2', '\x2', '\x30', '\x31', '\a', 'v', '\x2', '\x2', '\x31', 
		'\x32', '\a', 'j', '\x2', '\x2', '\x32', '\x6', '\x3', '\x2', '\x2', '\x2', 
		'\x33', '\x34', '\a', '.', '\x2', '\x2', '\x34', '\b', '\x3', '\x2', '\x2', 
		'\x2', '\x35', '\x36', '\a', '<', '\x2', '\x2', '\x36', '\n', '\x3', '\x2', 
		'\x2', '\x2', '\x37', '\x38', '\a', '\x41', '\x2', '\x2', '\x38', '\f', 
		'\x3', '\x2', '\x2', '\x2', '\x39', ':', '\a', '\x65', '\x2', '\x2', ':', 
		';', '\a', 'n', '\x2', '\x2', ';', '<', '\a', '\x63', '\x2', '\x2', '<', 
		'=', '\a', 'u', '\x2', '\x2', '=', '>', '\a', 'u', '\x2', '\x2', '>', 
		'\xE', '\x3', '\x2', '\x2', '\x2', '?', '@', '\a', 'k', '\x2', '\x2', 
		'@', '\x41', '\a', 'p', '\x2', '\x2', '\x41', '\x42', '\a', 'v', '\x2', 
		'\x2', '\x42', '\x43', '\a', 'g', '\x2', '\x2', '\x43', '\x44', '\a', 
		't', '\x2', '\x2', '\x44', '\x45', '\a', 'h', '\x2', '\x2', '\x45', '\x46', 
		'\a', '\x63', '\x2', '\x2', '\x46', 'G', '\a', '\x65', '\x2', '\x2', 'G', 
		'H', '\a', 'g', '\x2', '\x2', 'H', '\x10', '\x3', '\x2', '\x2', '\x2', 
		'I', 'J', '\a', 't', '\x2', '\x2', 'J', 'K', '\a', 'g', '\x2', '\x2', 
		'K', 'L', '\a', '\x65', '\x2', '\x2', 'L', 'M', '\a', 'q', '\x2', '\x2', 
		'M', 'N', '\a', 't', '\x2', '\x2', 'N', 'O', '\a', '\x66', '\x2', '\x2', 
		'O', '\x12', '\x3', '\x2', '\x2', '\x2', 'P', 'Q', '\t', '\x2', '\x2', 
		'\x2', 'Q', '\x14', '\x3', '\x2', '\x2', '\x2', 'R', 'S', '\t', '\x3', 
		'\x2', '\x2', 'S', '\x16', '\x3', '\x2', '\x2', '\x2', 'T', 'U', '\t', 
		'\x4', '\x2', '\x2', 'U', '\x18', '\x3', '\x2', '\x2', '\x2', 'V', 'W', 
		'\a', '\x61', '\x2', '\x2', 'W', '\x1A', '\x3', '\x2', '\x2', '\x2', 'X', 
		'\\', '\x5', '\x13', '\n', '\x2', 'Y', '\\', '\x5', '\x15', '\v', '\x2', 
		'Z', '\\', '\x5', '\x19', '\r', '\x2', '[', 'X', '\x3', '\x2', '\x2', 
		'\x2', '[', 'Y', '\x3', '\x2', '\x2', '\x2', '[', 'Z', '\x3', '\x2', '\x2', 
		'\x2', '\\', '\x1C', '\x3', '\x2', '\x2', '\x2', ']', '`', '\x5', '\x1B', 
		'\xE', '\x2', '^', '`', '\x5', '\x17', '\f', '\x2', '_', ']', '\x3', '\x2', 
		'\x2', '\x2', '_', '^', '\x3', '\x2', '\x2', '\x2', '`', '\x1E', '\x3', 
		'\x2', '\x2', '\x2', '\x61', '\x62', '\a', 'r', '\x2', '\x2', '\x62', 
		'\x63', '\a', 't', '\x2', '\x2', '\x63', '\x64', '\a', 'q', '\x2', '\x2', 
		'\x64', '\x65', '\a', 'r', '\x2', '\x2', '\x65', '\x66', '\a', 'g', '\x2', 
		'\x2', '\x66', 'g', '\a', 't', '\x2', '\x2', 'g', 'h', '\a', 'v', '\x2', 
		'\x2', 'h', 'i', '\a', '{', '\x2', '\x2', 'i', ' ', '\x3', '\x2', '\x2', 
		'\x2', 'j', 'n', '\x5', '\x1B', '\xE', '\x2', 'k', 'm', '\x5', '\x1D', 
		'\xF', '\x2', 'l', 'k', '\x3', '\x2', '\x2', '\x2', 'm', 'p', '\x3', '\x2', 
		'\x2', '\x2', 'n', 'l', '\x3', '\x2', '\x2', '\x2', 'n', 'o', '\x3', '\x2', 
		'\x2', '\x2', 'o', '\"', '\x3', '\x2', '\x2', '\x2', 'p', 'n', '\x3', 
		'\x2', '\x2', '\x2', 'q', 't', '\x5', '\x15', '\v', '\x2', 'r', 't', '\x5', 
		'\x13', '\n', '\x2', 's', 'q', '\x3', '\x2', '\x2', '\x2', 's', 'r', '\x3', 
		'\x2', '\x2', '\x2', 't', 'u', '\x3', '\x2', '\x2', '\x2', 'u', 's', '\x3', 
		'\x2', '\x2', '\x2', 'u', 'v', '\x3', '\x2', '\x2', '\x2', 'v', '$', '\x3', 
		'\x2', '\x2', '\x2', 'w', 'y', '\t', '\x5', '\x2', '\x2', 'x', 'w', '\x3', 
		'\x2', '\x2', '\x2', 'y', 'z', '\x3', '\x2', '\x2', '\x2', 'z', 'x', '\x3', 
		'\x2', '\x2', '\x2', 'z', '{', '\x3', '\x2', '\x2', '\x2', '{', '|', '\x3', 
		'\x2', '\x2', '\x2', '|', '}', '\b', '\x13', '\x2', '\x2', '}', '&', '\x3', 
		'\x2', '\x2', '\x2', '\t', '\x2', '[', '_', 'n', 's', 'u', 'z', '\x3', 
		'\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
